steps:  
- id:  'Rodando teste unitário'  
  name: 'gcr.io/cloud-builders/go'
  args: ['test', 'soma']
  env: ['GOPATH=/go']
- id:  'Push da imagem'   
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/soma', '.']
images: ['gcr.io/$PROJECT_ID/soma']
  
  


