steps: 
- id:  'Rodando teste unitário'  
  name: 'gcr.io/cloud-builders/go'
  env: ['GOPATH=/usr/local/go']
  args: ['test', 'soma']
 

- id:  'Push da imagem'   
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/soma', '.']
images: ['gcr.io/$PROJECT_ID/soma']
  
  


